-- Daily anniversary and birthday Web Push at 09:00 Asia/Seoul (00:00 UTC).

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create table if not exists public.notification_cron_secrets (
  name text primary key,
  secret text not null
);

alter table public.notification_cron_secrets enable row level security;
revoke all on public.notification_cron_secrets from anon, authenticated;
grant select on public.notification_cron_secrets to service_role;

insert into public.notification_cron_secrets (name, secret)
values (
  'date-reminders',
  replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')
)
on conflict (name) do nothing;

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  delivery_date date not null,
  event_type text not null check (event_type in ('anniversary', 'birthday')),
  event_key text not null,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  delivered_at timestamptz not null default now(),
  unique (delivery_date, event_type, event_key, recipient_id)
);

alter table public.notification_deliveries enable row level security;
revoke all on public.notification_deliveries from anon, authenticated;
grant select, insert, delete on public.notification_deliveries to service_role;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'coupledaily-date-reminders') then
    perform cron.unschedule('coupledaily-date-reminders');
  end if;
end
$$;

select cron.schedule(
  'coupledaily-date-reminders',
  '0 0 * * *',
  $job$
    select net.http_post(
      url := 'https://bqswnlvddquhzmlpwmks.supabase.co/functions/v1/send-date-reminders',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-secret', (
          select secret
          from public.notification_cron_secrets
          where name = 'date-reminders'
        )
      ),
      body := jsonb_build_object('scheduled_at', now())
    );
  $job$
);
